POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/getAIsuggestions
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "ISO27001",
    "number": 3
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/api
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "NIST"
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/storeControls
Content-Type: application/json
Accept: application/json

{
    "controls": [
        "ID: NIST SP 800-53 AC-20\nName: Use of External Information Systems\nDescription: Establish and implement controls to prevent unauthorized use of external information systems and to protect information when using external systems.",
        "ID: NIST SP 800-53 SC-8\nName: Transmission Confidentiality and Integrity\nDescription: Protect information in transit from unauthorized disclosure and modification.",
        "ID: NIST SP 800-53 AC-4\nName: Information Flow Enforcement\nDescription: Control the flow of information between designated sources and destinations within information systems."
    ],
    "metadatas": [
        {"source": "NIST SP 800-53 AC-20"},
        {"source": "NIST SP 800-53 SC-8"},
        {"source": "NIST SP 800-53 AC-4"}
    ]
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/deleteControl
Content-Type: application/json
Accept: application/json

{
    "control_id": "NIST SP 800-53 AC-4"
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/searchControl
Content-Type: application/json
Accept: application/json

{
    "control_id": "1"
}

###
GET https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/syncControls

### Control Api: get token
# @name login
GET https://happy-lemon.authentication.sap.hana.ondemand.com/oauth/token?grant_type=client_credentials
Authorization: Basic sb-6ecf26f0-c427-4d5b-ab10-44879ee658a4!b49874|control-controllibintegration!b4702 11bb4957-2f93-4815-8b8e-49502dfa44bf$kDT_12yzVJkKwHQ19rjN4xTTHVbYKLFAQKRHl15--ec=

@token = {{login.response.body.access_token}}
### Control Api: get control
GET https://GRCPCRMControlLibrary-controllibintegration-controllibrary-srv.cfapps.sap.hana.ondemand.com/odata/v4/ComplianceControlService/ComplianceControl
Authorization: Bearer {{token}}