POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/getAIsuggestions
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "ISO27001",
    "number": 3
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/api
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "NIST"
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/storeControls
Content-Type: application/json
Accept: application/json

{
    "controls": ["ID: NIST SP 800-53 AC-20\nName: Use of External Information Systems\nDescription: Establish and implement controls to prevent unauthorized use of external information systems and to protect information when using external systems.","ID: NIST SP 800-53 SC-8\nName: Transmission Confidentiality and Integrity\nDescription: Protect information in transit from unauthorized disclosure and modification.","ID: NIST SP 800-53 AC-4\nName: Information Flow Enforcement\nDescription: Control the flow of information between designated sources and destinations within information systems."]
}