POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/getAIsuggestions
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "ISO27001",
    "number": 3
}

###
POST https://risk-control-proposal-poc-beijia-playground.cfapps.sap.hana.ondemand.com/api
Content-Type: application/json
Accept: application/json

{
    "risk_info": "Confidential information is being sent to a non-secure email address",
    "risk_standard": "NIST"
}